#include "asset_browser_panel.hpp"
#include <imgui.h>
#include <algorithm>
#include <cctype>
#include <cstring>
#include <fstream>
#include <format>
#include <sstream>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>
#  include <shellapi.h>
#endif

namespace pf::editor {

namespace fs = std::filesystem;

// â”€â”€ Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

static std::string to_lower(std::string s) {
    for (char& c : s) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    return s;
}

bool AssetBrowserPanel::passes_filter(const FileEntry& fe) const {
    if (m_filter_buf[0] == '\0') return true;
    std::string needle = to_lower(m_filter_buf);
    return to_lower(fe.display_name).find(needle) != std::string::npos;
}

void AssetBrowserPanel::scan_directory(const std::string& dir, bool push_history) {
    if (push_history && !m_current_dir.empty())
        m_dir_stack.push_back(m_current_dir);

    m_entries.clear();
    m_selected_idx = -1;
    m_current_dir  = dir;
    m_preview.clear();

    std::error_code ec;
    if (!fs::is_directory(dir, ec)) return;

    // Add subdirectories first
    for (const auto& entry : fs::directory_iterator(dir, ec)) {
        if (entry.is_directory(ec)) {
            FileEntry fe;
            fe.path         = entry.path();
            fe.display_name = entry.path().filename().string() + "/";
            fe.ext          = "";
            fe.is_dir       = true;
            m_entries.push_back(std::move(fe));
        }
    }
    // Reset error code
    ec.clear();
    // Add files
    for (const auto& entry : fs::directory_iterator(dir, ec)) {
        if (entry.is_regular_file(ec)) {
            FileEntry fe;
            fe.path         = entry.path();
            fe.display_name = entry.path().filename().string();
            fe.ext          = to_lower(entry.path().extension().string());
            fe.is_dir       = false;
            m_entries.push_back(std::move(fe));
        }
    }

    // Sort: directories first, then files, both alphabetically
    std::sort(m_entries.begin(), m_entries.end(),
        [](const FileEntry& a, const FileEntry& b) {
            if (a.is_dir != b.is_dir) return a.is_dir > b.is_dir;
            return a.display_name < b.display_name;
        });
}

void AssetBrowserPanel::navigate_up() {
    if (!m_dir_stack.empty()) {
        std::string prev = m_dir_stack.back();
        m_dir_stack.pop_back();
        scan_directory(prev, false);
    } else if (!m_current_dir.empty()) {
        fs::path parent = fs::path(m_current_dir).parent_path();
        if (!parent.empty() && parent != fs::path(m_current_dir))
            scan_directory(parent.string(), false);
    }
}

void AssetBrowserPanel::load_preview(const FileEntry& fe) {
    if (fe.is_dir) { m_preview = "(directory)"; return; }
    std::ifstream f(fe.path);
    if (!f) { m_preview = "(cannot open file)"; return; }

    std::ostringstream ss;
    std::string line;
    int n = 0;
    while (std::getline(f, line) && n < 24) {
        ss << line << '\n';
        ++n;
    }
    if (!f.eof()) ss << "...\n";
    m_preview = ss.str();
}

void AssetBrowserPanel::open_in_explorer(const FileEntry& fe) const {
    fs::path p = fe.is_dir ? fe.path : fe.path.parent_path();
    std::string native = p.string();
#ifdef _WIN32
    ShellExecuteA(nullptr, "open", native.c_str(), nullptr, nullptr, SW_SHOW);
#else
    auto cmd = std::format("xdg-open \"{}\" 2>/dev/null &", native);
    std::system(cmd.c_str());
#endif
}

void AssetBrowserPanel::create_element_file(const std::string& name) const {
    if (m_current_dir.empty()) return;
    fs::path dest = fs::path(m_current_dir) /
                    (to_lower(name) + ".lua");
    if (fs::exists(dest)) return;

    std::ofstream f(dest);
    if (!f) return;
    f << std::format(
        "-- {0}.lua  (auto-generated by PixelForge Editor)\n"
        "define_element {{\n"
        "    name          = \"{0}\",\n"
        "    color         = 0xFFAAFF88,\n"
        "    physics       = \"solid\",\n"
        "    density       = 1.0,\n"
        "    flammability  = 0.0,\n"
        "}}\n", name);
}

// â”€â”€ Draw â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

void AssetBrowserPanel::draw(EditorContext& ctx) {
    ImGui::Begin("Asset Browser");

    // â”€â”€ Toolbar row 1: path bar â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    char root_buf[256]{};
    std::strncpy(root_buf, m_root_path.c_str(), sizeof(root_buf) - 1);
    ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 120.f);
    if (ImGui::InputText("##root", root_buf, sizeof(root_buf)))
        m_root_path = root_buf;
    ImGui::SameLine();
    if (ImGui::Button("Browse")) {
        scan_directory(m_root_path);
        m_status_msg.clear();
    }
    ImGui::SameLine();
    if (ImGui::Button("\u21ba")) {  // Refresh symbol
        scan_directory(m_current_dir.empty() ? m_root_path : m_current_dir, false);
        m_status_msg.clear();
    }

    // â”€â”€ Toolbar row 2: navigation + search â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    const bool can_go_up = !m_dir_stack.empty() ||
                           (fs::path(m_current_dir).has_parent_path() &&
                            fs::path(m_current_dir).parent_path() != fs::path(m_current_dir));
    if (!can_go_up) ImGui::BeginDisabled();
    if (ImGui::Button("<..")) navigate_up();
    if (!can_go_up) ImGui::EndDisabled();

    ImGui::SameLine();
    if (ImGui::SmallButton("elements/")) scan_directory(m_root_path + "elements/");
    ImGui::SameLine();
    if (ImGui::SmallButton("worlds/"))   scan_directory(m_root_path + "worlds/");
    ImGui::SameLine();
    if (ImGui::SmallButton("saves/"))    scan_directory(m_root_path + "saves/");

    // Search field
    ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x - 100.f);
    ImGui::InputText("Search##ab", m_filter_buf, sizeof(m_filter_buf));
    ImGui::SameLine();
    if (ImGui::Button("New Element")) {
        m_show_new_element_dlg = true;
        m_new_element_name[0] = '\0';
    }

    // Current path breadcrumb
    if (!m_current_dir.empty())
        ImGui::TextDisabled("  %s", m_current_dir.c_str());

    // â”€â”€ New-element dialog â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    if (m_show_new_element_dlg) {
        ImGui::OpenPopup("New Element##popup");
        m_show_new_element_dlg = false;
    }
    if (ImGui::BeginPopupModal("New Element##popup", nullptr,
                                ImGuiWindowFlags_AlwaysAutoResize)) {
        ImGui::Text("Element name (becomes <name>.lua):");
        ImGui::SetNextItemWidth(220.f);
        ImGui::InputText("##newname", m_new_element_name, sizeof(m_new_element_name));
        ImGui::Separator();
        if (ImGui::Button("Create") && m_new_element_name[0] != '\0') {
            create_element_file(m_new_element_name);
            scan_directory(m_current_dir, false);
            m_status_msg = std::format("Created '{}.lua'", m_new_element_name);
            m_status_ok  = true;
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("Cancel")) ImGui::CloseCurrentPopup();
        ImGui::EndPopup();
    }

    // â”€â”€ File list + preview split â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    const float panel_h = ImGui::GetContentRegionAvail().y - 36.f;
    if (panel_h < 50.f) { ImGui::End(); return; }

    ImGui::Columns(2, "##ab_cols", true);
    ImGui::SetColumnWidth(0, 200.f);

    // Left: file list
    ImGui::BeginChild("##filelist", {0.f, panel_h}, false);

    if (m_entries.empty()) {
        ImGui::TextDisabled("(empty â€” press Browse)");
    }

    for (int i = 0; i < static_cast<int>(m_entries.size()); ++i) {
        const auto& fe = m_entries[i];
        if (!passes_filter(fe)) continue;

        // Colour by type
        ImVec4 col{0.8f, 0.8f, 0.8f, 1.f};
        if      (fe.is_dir)          col = {0.95f, 0.85f, 0.40f, 1.f};
        else if (fe.ext == ".lua")   col = {0.60f, 0.90f, 1.00f, 1.f};
        else if (fe.ext == ".toml")  col = {1.00f, 0.85f, 0.50f, 1.f};
        else if (fe.ext == ".pfw")   col = {0.60f, 1.00f, 0.60f, 1.f};

        ImGui::PushStyleColor(ImGuiCol_Text, col);
        const bool sel = (i == m_selected_idx);
        if (ImGui::Selectable(fe.display_name.c_str(), sel,
                              ImGuiSelectableFlags_AllowDoubleClick)) {
            m_selected_idx = i;
            load_preview(fe);
            m_status_msg.clear();

            // Double-click action
            if (ImGui::IsMouseDoubleClicked(0)) {
                if (fe.is_dir) {
                    scan_directory(fe.path.string());
                } else if (fe.ext == ".pfw") {
                    ctx.save_path = fe.path.string();
                    m_status_msg = std::format("Save path set â€” use File > Load World");
                    m_status_ok  = false;
                } else if (fe.ext == ".toml") {
                    ctx.save_path = fe.path.string();
                    m_status_msg  = std::format("World config selected: '{}'", fe.display_name);
                    m_status_ok   = true;
                }
            }
        }
        ImGui::PopStyleColor();

        // Right-click context menu
        if (ImGui::BeginPopupContextItem()) {
            if (ImGui::MenuItem("Show in Explorer")) open_in_explorer(fe);
            if (!fe.is_dir) {
                ImGui::Separator();
                if (fe.ext == ".pfw" && ImGui::MenuItem("Set as Load/Save Path")) {
                    ctx.save_path = fe.path.string();
                    m_status_msg  = std::format("Save path: '{}'", fe.display_name);
                    m_status_ok   = true;
                }
            }
            ImGui::EndPopup();
        }
    }
    ImGui::EndChild();

    ImGui::NextColumn();

    // Right: preview + actions
    ImGui::BeginChild("##preview", {0.f, panel_h}, false);

    if (m_selected_idx >= 0 && m_selected_idx < static_cast<int>(m_entries.size())) {
        const auto& fe = m_entries[m_selected_idx];

        if (fe.is_dir) {
            ImGui::TextColored({0.95f, 0.85f, 0.4f, 1.f}, "[Dir]  %s",
                               fe.display_name.c_str());
            ImGui::TextDisabled("Double-click to navigate into directory.");
        } else {
            ImGui::TextColored({1.f, 1.f, 0.5f, 1.f}, "%s", fe.display_name.c_str());
            ImGui::TextDisabled("%s", fe.path.string().c_str());
            ImGui::Separator();

            // â”€â”€ Actions by file type â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            if (fe.ext == ".toml") {
                ImGui::TextColored({1.f, 0.85f, 0.5f, 1.f}, "TOML world config");
                ImGui::TextDisabled("Configure generation params and use the");
                ImGui::TextDisabled("World Gen panel to regenerate.");
                if (ImGui::Button("Set as World Config")) {
                    ctx.save_path = fe.path.string();
                    m_status_msg  = std::format("World config set to '{}'", fe.display_name);
                    m_status_ok   = true;
                }
            } else if (fe.ext == ".lua") {
                ImGui::TextColored({0.6f, 0.9f, 1.f, 1.f}, "Lua element definition");
                ImGui::TextDisabled("Use the Element Editor panel to modify.");
                ImGui::TextDisabled("Reload via Scripting system (Phase 9).");
            } else if (fe.ext == ".pfw") {
                ImGui::TextColored({0.6f, 1.f, 0.6f, 1.f}, "PixelForge world save");
                if (ImGui::Button("Set as Load Path")) {
                    ctx.save_path = fe.path.string();
                    m_status_msg  = std::format("Save path set \u2014 use File > Load World");
                    m_status_ok   = false;
                }
            }
            ImGui::SameLine();
            if (ImGui::Button("Show in Explorer")) open_in_explorer(fe);

            // â”€â”€ Preview â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
            ImGui::Spacing();
            const float preview_h = ImGui::GetContentRegionAvail().y - 24.f;
            if (preview_h > 40.f && !fe.is_dir) {
                ImGui::InputTextMultiline("##preview_text",
                    m_preview.data(),
                    m_preview.size(),
                    {-1.f, preview_h},
                    ImGuiInputTextFlags_ReadOnly);
            }
        }
    } else {
        ImGui::TextDisabled("Select a file to preview.");
    }

    ImGui::EndChild();
    ImGui::Columns(1);

    // â”€â”€ Status bar â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    if (!m_status_msg.empty()) {
        ImGui::Separator();
        ImGui::TextColored(m_status_ok
                           ? ImVec4{0.4f, 1.f, 0.5f, 1.f}
                           : ImVec4{1.f, 0.85f, 0.3f, 1.f},
                           "%s", m_status_msg.c_str());
    }

    ImGui::End();
}

} // namespace pf::editor
